/**
 * Browser-targeted production bundle for Projects Engine.
 *
 * The plugin runs inside Obsidian's Chromium / WKWebView / Android WebView
 * hosts — never in Node.js. This file itself executes in Node (the build
 * machine) but the emitted `main.js` must not import Node builtins such as
 * `fs`, `path`, or `crypto`. Accidental imports fail the build instead of
 * becoming runtime `require()` calls that crash on mobile.
 */
import esbuild from "esbuild";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

/**
 * Node.js builtins that must never appear in plugin source.
 * `node:`-prefixed specifiers are also rejected.
 */
const NODE_BUILTINS = [
	"assert",
	"async_hooks",
	"buffer",
	"child_process",
	"cluster",
	"console",
	"constants",
	"crypto",
	"dgram",
	"diagnostics_channel",
	"dns",
	"domain",
	"events",
	"fs",
	"http",
	"http2",
	"https",
	"inspector",
	"module",
	"net",
	"os",
	"path",
	"perf_hooks",
	"process",
	"punycode",
	"querystring",
	"readline",
	"repl",
	"stream",
	"string_decoder",
	"sys",
	"timers",
	"tls",
	"trace_events",
	"tty",
	"url",
	"util",
	"v8",
	"vm",
	"wasi",
	"worker_threads",
	"zlib",
];

const nodeBuiltinPattern = new RegExp(
	`^(node:)?(${NODE_BUILTINS.join("|")})(/.*)?$`,
);

/**
 * esbuild plugin that fails the build if plugin source (or a dependency)
 * resolves to a Node.js builtin. This is stricter than marking builtins as
 * `external`, which would only postpone the failure to mobile runtime.
 *
 * @returns {import('esbuild').Plugin}
 */
function banNodeBuiltins() {
	return {
		name: "ban-node-builtins",
		setup(build) {
			build.onResolve({ filter: nodeBuiltinPattern }, (args) => {
				return {
					errors: [
						{
							text: `Node.js builtin "${args.path}" is forbidden in Projects Engine. Use Web APIs or the Obsidian API (mobile-safe).`,
							location: null,
						},
					],
				};
			});
		},
	};
}

const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	platform: "browser",
	target: "es2021",
	format: "cjs",
	// Obsidian injects these at runtime; they must not be bundled.
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
	],
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	mainFields: ["browser", "module", "main"],
	conditions: ["browser"],
	plugins: [banNodeBuiltins()],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
}
